alias tls="tmux list-sessions"
alias tas="tmux attach-session -t"
alias trm="tmux kill-session -t"
alias tkill="tmux kill-server"
alias trename="tmux rename-session -t "
alias tsave="tmux-session save"
alias trestore="tmux-session restore"
alias trs="tmux-session restore"